# buildspec.yml
version: 0.2

phases:
  build:
    commands:
      - aws cloudformation deploy --template-file https://example.com/path/to/eks.yaml --stack-name MyEKSStack --capabilities CAPABILITY_IAM
