version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      # Install AWS CLI
      - pip install awscli
  build:
    commands:
      # Your build commands here, e.g., build your application
      - npm install
      - npm run build
  post_build:
    commands:
      # Push artifacts to S3 or perform any other post-build actions
      - aws s3 sync ./dist s3://sammutcicd/cloudformation
