version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      # Install AWS CLI
      - pip install awscli
  build:
    commands:
      # Fetch the CloudFormation template from GitHub and upload to S3
      - aws s3 cp https://raw.githubusercontent.com/sammutn90/sammuteks/main/Archived/eks.yaml s3://sammutcicd/cf/eks.yaml
  post_build:
    commands:
      # Output success message
      - echo "CloudFormation template uploaded to S3 successfully!"
