version: 0.2

phases:

  pre_build:
    commands:
      # Call the docker_setup.sh script to ensure Docker environment is set up correctly
      - ./docker_setup.sh
  build:
    commands:
      # Build the Docker image and tag it with the ECR repository URL
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker build -t 843960079237.dkr.ecr.us-east-1.amazonaws.com/sammutecr:latest .
      - docker push 843960079237.dkr.ecr.us-east-1.amazonaws.com/sammutecr:latest