version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws s3 cp https://github.com/sammutn90/sammuteks/blob/main/Archived/eks.yaml s3://sammutcicd/
  post_build:
    commands:
