version: 0.2
phases:
  pre_build:
    commands:
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 843960079237.dkr.ecr.us-east-1.amazonaws.com/sammutecr:latest .
      - echo "Pushing Docker image to ECR..."
      - docker push 843960079237.dkr.ecr.us-east-1.amazonaws.com/sammutecr:latest
      