# buildspec.yml
version: 0.2

phases:
  build:
    commands:
      - aws cloudformation deploy --template-file https://github.com/sammutn90/sammuteks/blob/develop/Archived/eks.yaml --stack-name eks --capabilities CAPABILITY_IAM
